# Generated by Django 2.1.1 on 2018-09-27 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=8)),
                ('rua', models.CharField(max_length=254)),
                ('bairro', models.CharField(max_length=254)),
                ('cidade', models.CharField(max_length=254)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='imoveis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_aluguel', models.DecimalField(decimal_places=2, max_digits=19)),
                ('quartos', models.PositiveIntegerField()),
                ('suites', models.PositiveIntegerField()),
                ('iptu', models.DecimalField(decimal_places=2, max_digits=19)),
                ('condominio', models.DecimalField(decimal_places=2, max_digits=19)),
                ('descricao', models.TextField()),
                ('imagens', models.ImageField(upload_to='')),
            ],
        ),
    ]
