# Generated by Django 2.1.1 on 2018-09-28 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imoveis',
            name='endereco',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro_imoveis.Endereco'),
        ),
    ]
